version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run unittests
          command: |
            . venv/bin/activate
            python -m unittest unittest.py

workflows:
  version: 2
  build:
    jobs:
      - build
